<a href="https://colab.research.google.com/github/Janhavi841/Machine_Learning/blob/main/Practice_sir_logistic_regr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/loan_logistic_regression_dataset.xlsx")

In [ ]:
#Target variable is Loan_Approved (0/1), we'll build a Logistic Regression model.

In [ ]:
df.head()

   Age  Monthly_Income  Credit_Score Gender Education_Level  Loan_Approved
0   26           37958           406   Male             PhD              0
1   47           34272           797   Male        Bachelor              1
2   25           28351           649   Male          Master              0
3   41           74724           786   Male          Master              1
4   45           51021           534   Male        Bachelor              0

In [ ]:
# Step 1: Import Libraries

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              50 non-null     int64
 1   Monthly_Income   50 non-null     int64
 2   Credit_Score     50 non-null     int64
 3   Gender           50 non-null     object
 4   Education_Level  50 non-null     object
 5   Loan_Approved    50 non-null     int64
dtypes: int64(4), object(2)
memory usage: 2.5+ KB

In [ ]:
# Step 4: Check Missing Values

In [ ]:
df.isnull().sum()

Age                0
Monthly_Income     0
Credit_Score       0
Gender             0
Education_Level    0
Loan_Approved      0
dtype: int64

In [ ]:
# Step 5: Separate Features and Target

In [ ]:
x = df.drop('Loan_Approved',axis=1)
y = df['Loan_Approved']

In [ ]:
# Step 6: Encode Categorical Columns

In [ ]:
x = pd.get_dummies(x,drop_first=True)

In [ ]:
x.head()

,Age,Monthly_Income,Credit_Score,Gender_Male,Education_Level_High School,Education_Level_Master,Education_Level_PhD
0,26,37958,406,True,False,False,True
1,47,34272,797,True,False,False,False
2,25,28351,649,True,False,True,False
3,41,74724,786,True,False,True,False
4,45,51021,534,True,False,False,False

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x,y,test_size=0.2,random_state=20
)

In [ ]:
X_train.head()

,Age,Monthly_Income,Credit_Score,Gender_Male,Education_Level_High School,Education_Level_Master,Education_Level_PhD
40,51,70192,569,True,False,True,False
17,29,60520,769,True,False,False,False
18,22,86726,385,False,False,False,False
0,26,37958,406,True,False,False,True
27,36,75741,335,True,False,True,False

In [ ]:
y_train.head()

40    1
17    1
18    0
0     0
27    0
Name: Loan_Approved, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 0])

In [ ]:
import statsmodels.api as sm
X_train_const = sm.add_constant(X_train)

In [ ]:
# Fit the logistic regression model
# Note: statsmodels expects data to be float/int, so convert bool columns if necessary
sm_model = sm.Logit(y_train, X_train_const.astype(pfloat)).fit_regularized(method='l1',alpha=0.1)
print(sm_model.summary())

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.11355637258222051
            Iterations: 99
            Function evaluations: 114
            Gradient evaluations: 99
                           Logit Regression Results
==============================================================================
Dep. Variable:          Loan_Approved   No. Observations:                   40
Model:                          Logit   Df Residuals:                       32
Method:                           MLE   Df Model:                            7
Date:                Sat, 27 Jun 2026   Pseudo R-squ.:                  0.9469
Time:                        06:22:32   Log-Likelihood:                -1.4721
converged:                       True   LL-Null:                       -27.726
Covariance Type:            nonrobust   LLR p-value:                 4.637e-09
===============================================================================================
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                         -28.3591     10.420     -2.722      0.006     -48.782      -7.936
Age                             0.1504      0.110      1.367      0.172      -0.065       0.366
Monthly_Income                  0.0001   4.92e-05      2.065      0.039    5.18e-06       0.000
Credit_Score                    0.0282      0.012      2.395      0.017       0.005       0.051
Gender_Male                    -0.2941      2.164     -0.136      0.892      -4.536       3.947
Education_Level_High School    -1.7504      3.295     -0.531      0.595      -8.208       4.708
Education_Level_Master          0.0643      2.963      0.022      0.983      -5.744       5.872
Education_Level_PhD             0.0546      3.457      0.016      0.987      -6.721       6.830
===============================================================================================

/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2385: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/usr/local/lib/python3.12/dist-packages/statsmodels/discrete/discrete_model.py:2443: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))
/usr/local/lib/python3.12/dist-packages/statsmodels/base/l1_solvers_common.py:71: ConvergenceWarning: QC check did not pass for 1 out of 8 parameters
Try increasing solver accuracy or number of iterations, decreasing alpha, or switch solvers
  warnings.warn(message, ConvergenceWarning)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/l1_solvers_common.py:144: ConvergenceWarning: Could not trim params automatically due to failed QC check. Trimming using trim_mode == 'size' will still work.
  warnings.warn(msg, ConvergenceWarning)

# **Logistic Regression On mtcars dataset**

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("/content/drive/MyDrive/CDAC_DataBook.xlsx", sheet_name="mtcars")

In [ ]:
data.head()

    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [ ]:
data = data.drop(["cyl",'disp','drat','qsec','vs','carb'], axis = 1)

In [ ]:
data.head()

    mpg   hp     wt  am  gear
0  21.0  110  2.620   1     4
1  21.0  110  2.875   1     4
2  22.8   93  2.320   1     4
3  21.4  110  3.215   0     3
4  18.7  175  3.440   0     3

In [ ]:
am_dummies = pd.get_dummies(data.am, drop_first=True).astype(int)
gear_dummies = pd.get_dummies(data.gear, drop_first = True).astype(int)

In [ ]:
data = pd.concat([data, am_dummies, gear_dummies],axis = 1)

In [ ]:
data.head()

    mpg   hp     wt  am  gear  1  4  5
0  21.0  110  2.620   1     4  1  1  0
1  21.0  110  2.875   1     4  1  1  0
2  22.8   93  2.320   1     4  1  1  0
3  21.4  110  3.215   0     3  0  0  0
4  18.7  175  3.440   0     3  0  0  0

In [ ]:
data = data.drop(['am','gear'],axis = 1)

In [ ]:
data.head()

    mpg   hp     wt  1  4  5
0  21.0  110  2.620  1  1  0
1  21.0  110  2.875  1  1  0
2  22.8   93  2.320  1  1  0
3  21.4  110  3.215  0  0  0
4  18.7  175  3.440  0  0  0

In [ ]:
data['mpg'].median()

19.2

In [ ]:
import numpy as np

In [ ]:
data['new_mpg'] = np.where(data['mpg'] > data['mpg'].median(),1,0)

In [ ]:
data.head()

    mpg   hp     wt  1  4  5  new_mpg
0  21.0  110  2.620  1  1  0        1
1  21.0  110  2.875  1  1  0        1
2  22.8   93  2.320  1  1  0        1
3  21.4  110  3.215  0  0  0        1
4  18.7  175  3.440  0  0  0        0

In [ ]:
data = data.drop(['mpg'], axis=1)

In [ ]:
data.head()

    hp     wt  1  4  5  new_mpg
0  110  2.620  1  1  0        1
1  110  2.875  1  1  0        1
2   93  2.320  1  1  0        1
3  110  3.215  0  0  0        1
4  175  3.440  0  0  0        0

In [ ]:
x = data.drop(["new_mpg"],axis=1)
y = data.new_mpg

In [ ]:
y.head()

0    1
1    1
2    1
3    1
4    0
Name: new_mpg, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=20, test_size=0.2)

In [ ]:
import statsmodels.api as sm

In [ ]:
x_train = sm.add_constant(x_train)
x_test = sm.add_constant(x_test)

In [ ]:
x_train.head()

    const   hp     wt  1  4  5
13    1.0  180  3.780  0  0  0
18    1.0   52  1.615  1  1  0
21    1.0  150  3.520  0  0  0
12    1.0  180  3.730  0  0  0
23    1.0  245  3.840  0  0  0

In [ ]:
model = sm.Logit(y_train, x_train).fit() # log of odds ratio

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.000000
         Iterations: 35

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [ ]:
print(model.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:                new_mpg   No. Observations:                   25
Model:                          Logit   Df Residuals:                       19
Method:                           MLE   Df Model:                            5
Date:                Tue, 30 Jun 2026   Pseudo R-squ.:                   1.000
Time:                        03:40:59   Log-Likelihood:            -5.9719e-07
converged:                      False   LL-Null:                       -17.148
Covariance Type:            nonrobust   LLR p-value:                 2.078e-06
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        431.5439   3.72e+04      0.012      0.991   -7.24e+04    7.32e+04
hp            -0.1025    101.496     -0.001      0.999    -199.030     198.825
wt          -126.0346    1.1e+04     -0.011      0.991   -2.17e+04    2.14e+04
1            -66.2305   1.67e+04     -0.004      0.997   -3.28e+04    3.27e+04
4             -4.9199   8385.523     -0.001      1.000   -1.64e+04    1.64e+04
5             42.5967   2.25e+04      0.002      0.998   -4.42e+04    4.42e+04
==============================================================================

Complete Separation: The results show that there iscomplete separation or perfect prediction.
In this case the Maximum Likelihood Estimator does not exist and the parameters
are not identified.

In [ ]:
how contineus data split in decision tree